CREATE OR REPLACE TYPE ADRESSE_TYPE AS OBJECT
(
    NUM_RUE   NUMBER,
    NOM_RUE   VARCHAR2(50),
    NOM_VILLE VARCHAR2(50)
)
/

CREATE OR REPLACE TYPE COURS_TYPE AS OBJECT
(
    NUM_COURS NUMBER(2),
    NOM       VARCHAR2(20),
    NBHEURES  NUMBER(2),
    ANNEE     NUMBER(1)
)
/

CREATE OR REPLACE TYPE LIST_COURS_TYPE AS VARRAY (5) OF COURS_TYPE
/

CREATE OR REPLACE TYPE UE_TYPE AS OBJECT
(
    NOM   varchar2(50),
    COURS LIST_COURS_TYPE
)
/

CREATE OR REPLACE TYPE RESULTAT_TYPE AS OBJECT
(
    NOM_COURS varchar2(50),
    POINTS    integer
)
/

CREATE OR REPLACE TYPE RESULTATS_TYPE AS TABLE OF RESULTAT_TYPE
/

CREATE OR REPLACE TYPE PERSONNE_TYPE AS OBJECT
(
    NUM_PERSONNE NUMBER(4),
    NOM          VARCHAR2(25),
    PRENOM       VARCHAR2(25)
) NOT FINAL
/

CREATE OR REPLACE TYPE ELEVE_TYPE UNDER PERSONNE_TYPE
(
    DATE_NAISSANCE DATE,
    POIDS          Number,
    ANNEE          Number,
    ADRESSE        ADRESSE_TYPE,
    RESULTAT       RESULTATS_TYPE
) FINAL
/

CREATE TABLE PERSONNES OF PERSONNE_TYPE
(
    CONSTRAINT PK_PERSONNES             PRIMARY KEY(NUM_PERSONNE),
    CONSTRAINT NN_PERSONNES_NOM         CHECK(NOM IS NOT NULL),
    CONSTRAINT NN_PERSONNES_PRENOM      CHECK(PRENOM IS NOT NULL)
)
/

CREATE TABLE UE OF UE_TYPE
(
    CONSTRAINT PK_UE PRIMARY KEY (NOM)
)
/

CREATE TABLE ELEVE OF ELEVE_TYPE NESTED TABLE RESULTAT STORE AS TABRESULT
/