CREATE TABLE PERSONNES OF PERSONNE_TYPE(
    CONSTRAINT PK_PERSONNES             PRIMARY KEY(NUM_PERSONNE),
    CONSTRAINT NN_PERSONNES_NOM         CHECK(NOM IS NOT NULL),
    CONSTRAINT NN_PERSONNES_PRENOM      CHECK(PRENOM IS NOT NULL),
    CONSTRAINT CK_PERSONNES_SEXE        CHECK(SEXE IN ('M', 'M', 'F', 'f', NULL))
)
/

CREATE TABLE ACTIVITES OF ACTIVITES_TYPE(
    CONSTRAINT PK_ACTIVITES             PRIMARY KEY(NIVEAU, NOM)
)
/

CREATE TABLE COURS OF COURS_TYPE(
    CONSTRAINT PK_COURS                PRIMARY KEY(NUM_COURS),
    CONSTRAINT NN_COURS_NOM            CHECK(NOM IS NOT NULL)
)
/

