CREATE OR REPLACE TYPE ADRESSE_TYPE AS OBJECT(
    NUM_RUE     NUMBER,
    NOM_RUE     VARCHAR2(50),
    NOM_VILLE   VARCHAR2(50)
)
/

CREATE OR REPLACE TYPE PERSONNE_TYPE AS OBJECT(
    NUM_PERSONNE    NUMBER (4),
    NOM             VARCHAR2(25),
    PRENOM          VARCHAR2(25),
    DATE_NAISSANCE  DATE,
    POIDS           NUMBER,
    ANNEE           NUMBER,
    SEXE	        CHAR (1)
)
/

CREATE OR REPLACE TYPE ACTIVITES_TYPE AS OBJECT(
    NIVEAU          NUMBER(1),
    NOM             VARCHAR2(20),
    EQUIPE          VARCHAR2(32)
)
/

CREATE OR REPLACE TYPE COURS_TYPE AS OBJECT(
    NUM_COURS       NUMBER(2),
    NOM             VARCHAR2(20),
    NBHEURES        NUMBER(2),
    ANNEE           NUMBER(1)
)
/
